### ISSUE TITLE
Example Compile Error

### ISSUE THREAD

**Issue by SerHanmer** [rhinostream/win_desktop_duplication#1]
When trying to compile either example from crates.io

"
   Compiling win_desktop_duplication v0.10.4
error[E0658]: deriving `Default` on enums is experimental
   --> C:\Users\SerHanmer\.cargo\registry\src\github.com-1ecc6299db9ec823\win_desktop_duplication-0.10.4\src\outputs.rs:264:30
    |
264 | #[derive(Clone, Copy, Debug, Default)]
    |                              ^^^^^^^
    |
    = note: see issue #86985 <https://github.com/rust-lang/rust/issues/86985> for more information
    = note: this error originates in the derive macro `Default` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0658]: deriving `Default` on enums is experimental
  --> C:\Users\SerHanmer\.cargo\registry\src\github.com-1ecc6299db9ec823\win_desktop_duplication-0.10.4\src\texture.rs:75:38
   |
75 | #[derive(Clone, Copy, Eq, PartialEq, Default, Debug)]
   |                                      ^^^^^^^
   |
   = note: see issue #86985 <https://github.com/rust-lang/rust/issues/86985> for more information
   = note: this error originates in the derive macro `Default` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0658`.                                                                                    
error: could not compile `win_desktop_duplication` due to 2 previous errors  
"

**Comment by kittuov** [comment]
What was the version of rust u were using

**Comment by kittuov** [comment]
@SerHanmer what was the rust version when you compiled this?

**Comment by kittuov** [comment]
[[Rust 1.62 Release Notes](https://blog.rust-lang.org/2022/06/30/Rust-1.62.0.html#default-enum-variants)] In Rust 1.62, this feature is made stable. It should work as expected if you update rust compiler with `rustup`. If that's not an option, I'll try to add `impl Default` for each enum. But it'll take me some time as i'm working on something else right now. 

if you open a pull request, I'll merge and push to `crates.io` as next update.

**Comment by kittuov** [comment]
I'm closing this issue because it's a rust version issue. Feel free to reopen if this issue is important to you
