### ISSUE TITLE
Get Data for Region-Specific Screen Capture

### ISSUE THREAD

**Issue by 0Ky** [rhinostream/win_desktop_duplication#2]
How do I `get_data` starting from a specific `x` and `y` coordinate?
Which would be useful if I want to capture certain area of the screen. 

Edit: Please review my #3 pull request.

**Comment by kittuov** [comment]
To achieve this, please use the texreader api and process the image that way. 

The main goal of this library is to produce full frames at a stable and predictable framerate. To be processed in GPU. Cropping these images is out of scope for this library. You can however access these images with subregion of total image using dx11 apis
